### PR TITLE
added test and fixed bug found

### PR DESCRIPTION
**Pull request by dbogs425**

### CODE REVIEW

**Comment by japesinator** [comment]
🙌 🙌 🙌

**Comment by japesinator** [comment]
will review + merge monday!

**Comment by ggrieco-tob** [comment]
Which bug was fixed?

**Comment by dbogs425** [comment]
After running the test I created to see if the types were changed I received this error:

> ━━━ Exception: ErrorCall ━━━
>        ┃   │ Arrays must only contain statically sized types
>        ┃   │ CallStack (from HasCallStack):
>        ┃   │   error, called at lib/Echidna/ABI.hs:120:8 in echidna-0.0.0.1-5kUNDQJ51NKGwUheqAFj8B:Echidna.ABI

To fix this, I changed genAbiType to genStaticAbiType within the genAbiValue function

**Comment by dguido** [comment]
Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/check/trailofbits/echidna?pullRequest=52) before we can accept your contribution. Please click through this link when signed into your Github account and we're all set! https://cla-assistant.io/check/trailofbits/echidna?pullRequest=52

**Comment by dguido** [comment]
@dbogs425 poke! Please sign our CLA, we'd love to get this included in Echidna.

**Comment by ggrieco-tob** [comment]
hey @dbogs425, can you fix the [compilation error](https://travis-ci.org/trailofbits/echidna/jobs/408184251#L629-L630) adding the missing instance?

**Comment by japesinator** [comment]
Great idea, not currently viable due to weird performance issues. Maybe revisit later?

**Pull request closed without merging**
